"""message

Revision ID: abef060b8ccc
Revises: dd93b474f5e4
Create Date: 2025-01-24 13:19:10.057731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abef060b8ccc'
down_revision = 'dd93b474f5e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
